package com.acsm.ytcollege.entity;// default package
// Generated 2017-12-19 15:31:33 by Hibernate Tools 3.4.0.CR1

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * DataDic generated by hbm2java
 */
@Entity
@Table(name = "data_dic", catalog = "job_acsm")
public class DataDic implements java.io.Serializable {

	private Integer id;
	private Integer dicId;
	private String dicName;

	public DataDic() {
	}

	public DataDic(Integer dicId, String dicName) {
		this.dicId = dicId;
		this.dicName = dicName;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "id", unique = true, nullable = false)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@Column(name = "dic_id")
	public Integer getDicId() {
		return this.dicId;
	}

	public void setDicId(Integer dicId) {
		this.dicId = dicId;
	}

	@Column(name = "dic_name", length = 200)
	public String getDicName() {
		return this.dicName;
	}

	public void setDicName(String dicName) {
		this.dicName = dicName;
	}

}
