package com.acsm.ytcollege.entity;// default package
// Generated 2017-12-19 23:46:57 by Hibernate Tools 3.4.0.CR1

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * EnterprisePosition generated by hbm2java
 */
@Entity
@Table(name = "enterprise_position", catalog = "job_acsm")
public class EnterprisePosition implements java.io.Serializable {

	private Integer positionId;
	private String positionName;
	private Integer typesId;
//	private Integer salaryId;
	private Integer salaryMinId;
	private Integer salaryMaxId;
	private Integer experience;
	private Integer degreeId;
	private Integer benefits;
	private Integer recruitNum;
	private String positionDescribe;
	private String workAddress;
	private Date insertTime;
	private Date expirationTime;
	private Integer isDeleted;
	private Integer state;
	private Integer enterpriseId;

	public EnterprisePosition() {
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "position_id", unique = true, nullable = false)
	public Integer getPositionId() {
		return this.positionId;
	}

	public void setPositionId(Integer positionId) {
		this.positionId = positionId;
	}

	@Column(name = "position_name", length = 200)
	public String getPositionName() {
		return this.positionName;
	}

	public void setPositionName(String positionName) {
		this.positionName = positionName;
	}

	@Column(name = "types_id")
	public Integer getTypesId() {
		return this.typesId;
	}

	public void setTypesId(Integer typesId) {
		this.typesId = typesId;
	}

	@Column(name = "experience")
	public Integer getExperience() {
		return this.experience;
	}

	public void setExperience(Integer experience) {
		this.experience = experience;
	}

	@Column(name = "degree_id")
	public Integer getDegreeId() {
		return this.degreeId;
	}

	public void setDegreeId(Integer degreeId) {
		this.degreeId = degreeId;
	}

	@Column(name = "benefits")
	public Integer getBenefits() {
		return this.benefits;
	}

	public void setBenefits(Integer benefits) {
		this.benefits = benefits;
	}

	@Column(name = "recruit_num")
	public Integer getRecruitNum() {
		return this.recruitNum;
	}

	public void setRecruitNum(Integer recruitNum) {
		this.recruitNum = recruitNum;
	}

	@Column(name = "position_describe", length = 500)
	public String getPositionDescribe() {
		return this.positionDescribe;
	}

	public void setPositionDescribe(String positionDescribe) {
		this.positionDescribe = positionDescribe;
	}

	@Column(name = "work_address", length = 200)
	public String getWorkAddress() {
		return this.workAddress;
	}

	public void setWorkAddress(String workAddress) {
		this.workAddress = workAddress;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "insert_time", length = 19)
	public Date getInsertTime() {
		return this.insertTime;
	}

	public void setInsertTime(Date insertTime) {
		this.insertTime = insertTime;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "expiration_time", length = 19)
	public Date getExpirationTime() {
		return this.expirationTime;
	}

	public void setExpirationTime(Date expirationTime) {
		this.expirationTime = expirationTime;
	}

	@Column(name = "is_deleted")
	public Integer getIsDeleted() {
		return this.isDeleted;
	}

	public void setIsDeleted(Integer isDeleted) {
		this.isDeleted = isDeleted;
	}

	@Column(name = "state")
	public Integer getState() {
		return this.state;
	}

	public void setState(Integer state) {
		this.state = state;
	}

	@Column(name = "enterprise_id")
	public Integer getEnterpriseId() {
		return this.enterpriseId;
	}

	public void setEnterpriseId(Integer enterpriseId) {
		this.enterpriseId = enterpriseId;
	}

	@Column(name = "salary_min_id")
	public Integer getSalaryMinId() {
		return salaryMinId;
	}

	public void setSalaryMinId(Integer salaryMinId) {
		this.salaryMinId = salaryMinId;
	}
	@Column(name = "salary_max_id")
	public Integer getSalaryMaxId() {
		return salaryMaxId;
	}

	public void setSalaryMaxId(Integer salaryMaxId) {
		this.salaryMaxId = salaryMaxId;
	}

}
