package com.acsm.ytcollege.entity;

// Generated 2017-12-15 18:34:17 by Hibernate Tools 3.4.0.CR1

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * JobConcernPosition generated by hbm2java
 */
@Entity
@Table(name = "job_concern_position", catalog = "yt_college")
public class JobConcernPosition implements java.io.Serializable {

	private Integer concernPositionId;
	private Integer userId;
	private Integer positionId;
	private Integer isDeleted;

	public JobConcernPosition() {
	}

	public JobConcernPosition(Integer userId, Integer positionId,
			Integer isDeleted) {
		this.userId = userId;
		this.positionId = positionId;
		this.isDeleted = isDeleted;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "concern position_id", unique = true, nullable = false)
	public Integer getConcernPositionId() {
		return this.concernPositionId;
	}

	public void setConcernPositionId(Integer concernPositionId) {
		this.concernPositionId = concernPositionId;
	}

	@Column(name = "user_id")
	public Integer getUserId() {
		return this.userId;
	}

	public void setUserId(Integer userId) {
		this.userId = userId;
	}

	@Column(name = "position_id")
	public Integer getPositionId() {
		return this.positionId;
	}

	public void setPositionId(Integer positionId) {
		this.positionId = positionId;
	}

	@Column(name = "is_deleted")
	public Integer getIsDeleted() {
		return this.isDeleted;
	}

	public void setIsDeleted(Integer isDeleted) {
		this.isDeleted = isDeleted;
	}

}
