package com.acsm.ytcollege.entity;

// Generated 2017-12-15 18:34:17 by Hibernate Tools 3.4.0.CR1

import javax.persistence.*;

import static javax.persistence.GenerationType.IDENTITY;

/**
 * JobEnterpriseInfo generated by hbm2java
 */
@Entity
@Table(name = "job_enterprise_info", catalog = "")
public class JobEnterpriseInfo implements java.io.Serializable {

	private int jobEnterpriseInfoId;
	private String logo;
	private String enterpriseName;
	private String enterpriseNature;
	private Integer enterpriseScale;
	private String recruitAddress;
	private String recruitPeople;
	private String phone;
	private String enterprisePresentation;
	private Integer authState;
	private Integer ytAccountId;

	public JobEnterpriseInfo() {
	}

	public JobEnterpriseInfo(int jobEntepriseInfoId) {
		this.jobEnterpriseInfoId = jobEntepriseInfoId;
	}

	public JobEnterpriseInfo(int jobEntepriseInfoId, String logo,
							 String enterpriseName, String enterpriseNature,
							 Integer enterpriseScale, String recruitAddress,
							 String recruitPeople, String phone, String enterprisePresentation,
							 Integer authState) {
		this.jobEnterpriseInfoId = jobEntepriseInfoId;
		this.logo = logo;
		this.enterpriseName = enterpriseName;
		this.enterpriseNature = enterpriseNature;
		this.enterpriseScale = enterpriseScale;
		this.recruitAddress = recruitAddress;
		this.recruitPeople = recruitPeople;
		this.phone = phone;
		this.enterprisePresentation = enterprisePresentation;
		this.authState = authState;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "job_enterprise_info_id", unique = true, nullable = false)
	public int getJobEntepriseInfoId() {
		return this.jobEnterpriseInfoId;
	}

	public void setJobEntepriseInfoId(int jobEntepriseInfoId) {
		this.jobEnterpriseInfoId = jobEntepriseInfoId;
	}

	@Column(name = "logo", length = 200)
	public String getLogo() {
		return this.logo;
	}

	public void setLogo(String logo) {
		this.logo = logo;
	}

	@Column(name = "enterprise_name", length = 45)
	public String getEnterpriseName() {
		return this.enterpriseName;
	}

	public void setEnterpriseName(String enterpriseName) {
		this.enterpriseName = enterpriseName;
	}

	@Column(name = "enterprise_nature", length = 45)
	public String getEnterpriseNature() {
		return this.enterpriseNature;
	}

	public void setEnterpriseNature(String enterpriseNature) {
		this.enterpriseNature = enterpriseNature;
	}

	@Column(name = "enterprise_scale")
	public Integer getEnterpriseScale() {
		return this.enterpriseScale;
	}

	public void setEnterpriseScale(Integer enterpriseScale) {
		this.enterpriseScale = enterpriseScale;
	}

	@Column(name = "recruit_address", length = 45)
	public String getRecruitAddress() {
		return this.recruitAddress;
	}

	public void setRecruitAddress(String recruitAddress) {
		this.recruitAddress = recruitAddress;
	}

	@Column(name = "recruit_people", length = 45)
	public String getRecruitPeople() {
		return this.recruitPeople;
	}

	public void setRecruitPeople(String recruitPeople) {
		this.recruitPeople = recruitPeople;
	}

	@Column(name = "phone", length = 45)
	public String getPhone() {
		return this.phone;
	}

	public void setPhone(String phone) {
		this.phone = phone;
	}

	@Column(name = "enterprise_presentation", length = 500)
	public String getEnterprisePresentation() {
		return this.enterprisePresentation;
	}

	public void setEnterprisePresentation(String enterprisePresentation) {
		this.enterprisePresentation = enterprisePresentation;
	}

	@Column(name = "auth_state")
	public Integer getAuthState() {
		return this.authState;
	}

	public void setAuthState(Integer authState) {
		this.authState = authState;
	}

	@Column(name = "yt_account_id")
	public int getYtAccountId() {
		return ytAccountId;
	}

	public void setYtAccountId(int ytAccountId) {
		this.ytAccountId = ytAccountId;
	}
}
