package com.acsm.ytcollege.entity;

// Generated 2017-12-15 18:34:17 by Hibernate Tools 3.4.0.CR1

import javax.persistence.*;
import java.util.Date;

import static javax.persistence.GenerationType.IDENTITY;

/**
 * JobResume generated by hbm2java
 */
@Entity
@Table(name = "job_resume", catalog = "yt_college")
public class JobResume implements java.io.Serializable {

	private Integer resumeId;
	private String resumeName;
	private Integer userId;
	private String ico;
	private String fullName;
	private Integer sex;
	private Date birthdate;
	private Date timeToWork;
	private Integer livingCityId;
	private Integer residentCityId;
	private String email;
	private String selfEvaluation;
	private Integer isDeleted;

	public JobResume() {
	}

	public JobResume(String resumeName, Integer userId, String ico,
			String fullName, Integer sex, Date birthdate, Date timeToWork,
			Integer livingCityId, Integer residentCityId, String email,
			String selfEvaluation, Integer isDeleted) {
		this.resumeName = resumeName;
		this.userId = userId;
		this.ico = ico;
		this.fullName = fullName;
		this.sex = sex;
		this.birthdate = birthdate;
		this.timeToWork = timeToWork;
		this.livingCityId = livingCityId;
		this.residentCityId = residentCityId;
		this.email = email;
		this.selfEvaluation = selfEvaluation;
		this.isDeleted = isDeleted;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "resume_id", unique = true, nullable = false)
	public Integer getResumeId() {
		return this.resumeId;
	}

	public void setResumeId(Integer resumeId) {
		this.resumeId = resumeId;
	}

	@Column(name = "resume_name", length = 100)
	public String getResumeName() {
		return this.resumeName;
	}

	public void setResumeName(String resumeName) {
		this.resumeName = resumeName;
	}

	@Column(name = "user_id")
	public Integer getUserId() {
		return this.userId;
	}

	public void setUserId(Integer userId) {
		this.userId = userId;
	}

	@Column(name = "ico", length = 100)
	public String getIco() {
		return this.ico;
	}

	public void setIco(String ico) {
		this.ico = ico;
	}

	@Column(name = "full_name", length = 45)
	public String getFullName() {
		return this.fullName;
	}

	public void setFullName(String fullName) {
		this.fullName = fullName;
	}

	@Column(name = "sex")
	public Integer getSex() {
		return this.sex;
	}

	public void setSex(Integer sex) {
		this.sex = sex;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "birthdate", length = 10)
	public Date getBirthdate() {
		return this.birthdate;
	}

	public void setBirthdate(Date birthdate) {
		this.birthdate = birthdate;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "time_to_work", length = 10)
	public Date getTimeToWork() {
		return this.timeToWork;
	}

	public void setTimeToWork(Date timeToWork) {
		this.timeToWork = timeToWork;
	}

	@Column(name = "living_city_id")
	public Integer getLivingCityId() {
		return this.livingCityId;
	}

	public void setLivingCityId(Integer livingCityId) {
		this.livingCityId = livingCityId;
	}

	@Column(name = "resident_city_id")
	public Integer getResidentCityId() {
		return this.residentCityId;
	}

	public void setResidentCityId(Integer residentCityId) {
		this.residentCityId = residentCityId;
	}

	@Column(name = "email", length = 50)
	public String getEmail() {
		return this.email;
	}

	public void setEmail(String email) {
		this.email = email;
	}

	@Column(name = "self_evaluation", length = 500)
	public String getSelfEvaluation() {
		return this.selfEvaluation;
	}

	public void setSelfEvaluation(String selfEvaluation) {
		this.selfEvaluation = selfEvaluation;
	}

	@Column(name = "is_deleted")
	public Integer getIsDeleted() {
		return this.isDeleted;
	}

	public void setIsDeleted(Integer isDeleted) {
		this.isDeleted = isDeleted;
	}

}
