package com.acsm.ytcollege.entity;

// Generated 2017-12-15 18:34:17 by Hibernate Tools 3.4.0.CR1

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * JobResumePersonalHonor generated by hbm2java
 */
@Entity
@Table(name = "job_resume_personal_honor", catalog = "yt_college")
public class JobResumePersonalHonor implements java.io.Serializable {

	private Integer personalHonorId;
	private Integer resumeId;
	private Integer certificateType;
	private String certificateName;
	private Date acquireTime;
	private String issued;
	private Integer isDeleted;

	public JobResumePersonalHonor() {
	}

	public JobResumePersonalHonor(Integer resumeId, Integer certificateType,
			String certificateName, Date acquireTime, String issued,
			Integer isDeleted) {
		this.resumeId = resumeId;
		this.certificateType = certificateType;
		this.certificateName = certificateName;
		this.acquireTime = acquireTime;
		this.issued = issued;
		this.isDeleted = isDeleted;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "personal_honor_id", unique = true, nullable = false)
	public Integer getPersonalHonorId() {
		return this.personalHonorId;
	}

	public void setPersonalHonorId(Integer personalHonorId) {
		this.personalHonorId = personalHonorId;
	}

	@Column(name = "resume_id")
	public Integer getResumeId() {
		return this.resumeId;
	}

	public void setResumeId(Integer resumeId) {
		this.resumeId = resumeId;
	}

	@Column(name = "certificate_type")
	public Integer getCertificateType() {
		return this.certificateType;
	}

	public void setCertificateType(Integer certificateType) {
		this.certificateType = certificateType;
	}

	@Column(name = "certificate_name", length = 100)
	public String getCertificateName() {
		return this.certificateName;
	}

	public void setCertificateName(String certificateName) {
		this.certificateName = certificateName;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "acquire_time", length = 10)
	public Date getAcquireTime() {
		return this.acquireTime;
	}

	public void setAcquireTime(Date acquireTime) {
		this.acquireTime = acquireTime;
	}

	@Column(name = "issued", length = 200)
	public String getIssued() {
		return this.issued;
	}

	public void setIssued(String issued) {
		this.issued = issued;
	}

	@Column(name = "is_deleted")
	public Integer getIsDeleted() {
		return this.isDeleted;
	}

	public void setIsDeleted(Integer isDeleted) {
		this.isDeleted = isDeleted;
	}

}
