package com.acsm.ytcollege.entity;

// Generated 2017-12-15 18:34:17 by Hibernate Tools 3.4.0.CR1

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * JobResumeEnterprisePay generated by hbm2java
 */
@Entity
@Table(name = "job_resume_enterprise_pay", catalog = "yt_college")
public class JobResumeEnterprisePay implements java.io.Serializable {

	private Integer enterprisePayId;
	private Integer resumeId;
	private Integer jobEnterpriseId;
	private Date insertTime;
	private Integer isDeleted;

	public JobResumeEnterprisePay() {
	}

	public JobResumeEnterprisePay(Integer resumeId, Integer jobEnterpriseId,
			Date insertTime, Integer isDeleted) {
		this.resumeId = resumeId;
		this.jobEnterpriseId = jobEnterpriseId;
		this.insertTime = insertTime;
		this.isDeleted = isDeleted;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "enterprise_pay_id", unique = true, nullable = false)
	public Integer getEnterprisePayId() {
		return this.enterprisePayId;
	}

	public void setEnterprisePayId(Integer enterprisePayId) {
		this.enterprisePayId = enterprisePayId;
	}

	@Column(name = "resume_id")
	public Integer getResumeId() {
		return this.resumeId;
	}

	public void setResumeId(Integer resumeId) {
		this.resumeId = resumeId;
	}

	@Column(name = "job_enterprise_id")
	public Integer getJobEnterpriseId() {
		return this.jobEnterpriseId;
	}

	public void setJobEnterpriseId(Integer jobEnterpriseId) {
		this.jobEnterpriseId = jobEnterpriseId;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "insert_time", length = 19)
	public Date getInsertTime() {
		return this.insertTime;
	}

	public void setInsertTime(Date insertTime) {
		this.insertTime = insertTime;
	}

	@Column(name = "is_deleted")
	public Integer getIsDeleted() {
		return this.isDeleted;
	}

	public void setIsDeleted(Integer isDeleted) {
		this.isDeleted = isDeleted;
	}

}
