package com.acsm.ytcollege.entity;

// Generated 2017-12-15 18:34:17 by Hibernate Tools 3.4.0.CR1

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * JobResumeEducationExperience generated by hbm2java
 */
@Entity
@Table(name = "job_resume_education_experience", catalog = "yt_college")
public class JobResumeEducationExperience implements java.io.Serializable {

	private Integer educationExperienceId;
	private Integer resumeId;
	private Integer schoolId;
	private Integer degreeId;
	private Date beginTime;
	private Date endTime;
	private Integer majorId;
	private Integer isDeleted;

	public JobResumeEducationExperience() {
	}

	public JobResumeEducationExperience(Integer resumeId, Integer schoolId,
			Integer degreeId, Date beginTime, Date endTime, Integer majorId,
			Integer isDeleted) {
		this.resumeId = resumeId;
		this.schoolId = schoolId;
		this.degreeId = degreeId;
		this.beginTime = beginTime;
		this.endTime = endTime;
		this.majorId = majorId;
		this.isDeleted = isDeleted;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "education_experience_id", unique = true, nullable = false)
	public Integer getEducationExperienceId() {
		return this.educationExperienceId;
	}

	public void setEducationExperienceId(Integer educationExperienceId) {
		this.educationExperienceId = educationExperienceId;
	}

	@Column(name = "resume_id")
	public Integer getResumeId() {
		return this.resumeId;
	}

	public void setResumeId(Integer resumeId) {
		this.resumeId = resumeId;
	}

	@Column(name = "school_id")
	public Integer getSchoolId() {
		return this.schoolId;
	}

	public void setSchoolId(Integer schoolId) {
		this.schoolId = schoolId;
	}

	@Column(name = "degree_id")
	public Integer getDegreeId() {
		return this.degreeId;
	}

	public void setDegreeId(Integer degreeId) {
		this.degreeId = degreeId;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "begin_time", length = 10)
	public Date getBeginTime() {
		return this.beginTime;
	}

	public void setBeginTime(Date beginTime) {
		this.beginTime = beginTime;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "end_time", length = 10)
	public Date getEndTime() {
		return this.endTime;
	}

	public void setEndTime(Date endTime) {
		this.endTime = endTime;
	}

	@Column(name = "major_id")
	public Integer getMajorId() {
		return this.majorId;
	}

	public void setMajorId(Integer majorId) {
		this.majorId = majorId;
	}

	@Column(name = "is_deleted")
	public Integer getIsDeleted() {
		return this.isDeleted;
	}

	public void setIsDeleted(Integer isDeleted) {
		this.isDeleted = isDeleted;
	}

}
