package com.acsm.ytcollege.entity;

// Generated 2017-12-15 18:34:17 by Hibernate Tools 3.4.0.CR1

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;
//import org.hibernate.validator.Length;

/**
 * JobResumeEmploymentRecord generated by hbm2java
 */
@Entity
@Table(name = "job_resume_employment_record", catalog = "")
public class JobResumeEmploymentRecord implements java.io.Serializable {

	private Integer employmentRecordId;
	private Integer resumeId;
	private String companyName;
	private Integer salaryMinId;
	private Integer salaryMaxId;
	private Date beginTime;
	private Date endTime;
	private Integer stationId;
	private String workDescribe;
	private Integer isDeleted;

	public JobResumeEmploymentRecord() {
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "employment_record_id", unique = true, nullable = false)
	public Integer getEmploymentRecordId() {
		return this.employmentRecordId;
	}

	public void setEmploymentRecordId(Integer employmentRecordId) {
		this.employmentRecordId = employmentRecordId;
	}

	@Column(name = "resume_id")
	public Integer getResumeId() {
		return this.resumeId;
	}

	public void setResumeId(Integer resumeId) {
		this.resumeId = resumeId;
	}

	@Column(name = "company_name", length = 200)
//	@Length(max = 200)
	public String getCompanyName() {
		return this.companyName;
	}

	public void setCompanyName(String companyName) {
		this.companyName = companyName;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "begin_time", length = 10)
	public Date getBeginTime() {
		return this.beginTime;
	}

	public void setBeginTime(Date beginTime) {
		this.beginTime = beginTime;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "end_time", length = 10)
	public Date getEndTime() {
		return this.endTime;
	}

	public void setEndTime(Date endTime) {
		this.endTime = endTime;
	}

	@Column(name = "station_id")
	public Integer getStationId() {
		return this.stationId;
	}

	public void setStationId(Integer stationId) {
		this.stationId = stationId;
	}

	@Column(name = "work_describe", length = 500)
//	@Length(max = 500)
	public String getWorkDescribe() {
		return this.workDescribe;
	}

	public void setWorkDescribe(String workDescribe) {
		this.workDescribe = workDescribe;
	}

	@Column(name = "is_deleted")
	public Integer getIsDeleted() {
		return this.isDeleted;
	}

	public void setIsDeleted(Integer isDeleted) {
		this.isDeleted = isDeleted;
	}

	@Column(name = "salary_min_id")
	public Integer getSalaryMinId() {
		return salaryMinId;
	}

	public void setSalaryMinId(Integer salaryMinId) {
		this.salaryMinId = salaryMinId;
	}
	@Column(name = "salary_max_id")
	public Integer getSalaryMaxId() {
		return salaryMaxId;
	}

	public void setSalaryMaxId(Integer salaryMaxId) {
		this.salaryMaxId = salaryMaxId;
	}

}
