package com.acsm.ytcollege.entity;// default package
// Generated 2017-12-17 20:51:00 by Hibernate Tools 3.4.0.CR1

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * JobResumePurpose generated by hbm2java
 */
@Entity
@Table(name = "job_resume_purpose", catalog = "yt_college")
public class JobResumePurpose implements java.io.Serializable {

	private Integer jobPurposeId;
	private Integer resumeId;
	private String jobCategoryId;
	private Integer workLocationId;
	private Integer jobTypesId;
	private Integer jobState;
	private Integer isDeleted;
	private Integer salaryMinId;
	private Integer salaryMaxId;



	public JobResumePurpose() {
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "job_purpose_id", unique = true, nullable = false)
	public Integer getJobPurposeId() {
		return this.jobPurposeId;
	}

	public void setJobPurposeId(Integer jobPurposeId) {
		this.jobPurposeId = jobPurposeId;
	}

	@Column(name = "resume_id")
	public Integer getResumeId() {
		return this.resumeId;
	}

	public void setResumeId(Integer resumeId) {
		this.resumeId = resumeId;
	}

	@Column(name = "job_category_id", length = 45)
	public String getJobCategoryId() {
		return this.jobCategoryId;
	}

	public void setJobCategoryId(String jobCategoryId) {
		this.jobCategoryId = jobCategoryId;
	}

	@Column(name = "work_location_id")
	public Integer getWorkLocationId() {
		return this.workLocationId;
	}

	public void setWorkLocationId(Integer workLocationId) {
		this.workLocationId = workLocationId;
	}

	@Column(name = "job_types_id")
	public Integer getJobTypesId() {
		return this.jobTypesId;
	}

	public void setJobTypesId(Integer jobTypesId) {
		this.jobTypesId = jobTypesId;
	}

	@Column(name = "job_state")
	public Integer getJobState() {
		return this.jobState;
	}

	public void setJobState(Integer jobState) {
		this.jobState = jobState;
	}

	@Column(name = "is_deleted")
	public Integer getIsDeleted() {
		return this.isDeleted;
	}

	public void setIsDeleted(Integer isDeleted) {
		this.isDeleted = isDeleted;
	}

	@Column(name = "salary_min_id")
	public Integer getSalaryMinId() {
		return salaryMinId;
	}

	public void setSalaryMinId(Integer salaryMinId) {
		this.salaryMinId = salaryMinId;
	}
	@Column(name = "salary_max_id")
	public Integer getSalaryMaxId() {
		return salaryMaxId;
	}

	public void setSalaryMaxId(Integer salaryMaxId) {
		this.salaryMaxId = salaryMaxId;
	}

}
