package com.acsm.ytcollege.entity;

// Generated 2017-12-15 18:34:17 by Hibernate Tools 3.4.0.CR1

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * JobSendRecord generated by hbm2java
 */
@Entity
@Table(name = "job_send_record", catalog = "yt_college")
public class JobSendRecord implements java.io.Serializable {

	private Integer sendRecordId;
	private Integer resumeId;
	private Integer positionId;
	private Integer state;
	private Date sendTime;
	private Date insertTime;

	public JobSendRecord() {
	}

	public JobSendRecord(Integer resumeId, Integer positionId, Integer state,
			Date sendTime, Date insertTime) {
		this.resumeId = resumeId;
		this.positionId = positionId;
		this.state = state;
		this.sendTime = sendTime;
		this.insertTime = insertTime;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "send_record_id", unique = true, nullable = false)
	public Integer getSendRecordId() {
		return this.sendRecordId;
	}

	public void setSendRecordId(Integer sendRecordId) {
		this.sendRecordId = sendRecordId;
	}

	@Column(name = "resume_id")
	public Integer getResumeId() {
		return this.resumeId;
	}

	public void setResumeId(Integer resumeId) {
		this.resumeId = resumeId;
	}

	@Column(name = "position_id")
	public Integer getPositionId() {
		return this.positionId;
	}

	public void setPositionId(Integer positionId) {
		this.positionId = positionId;
	}

	@Column(name = "state")
	public Integer getState() {
		return this.state;
	}

	public void setState(Integer state) {
		this.state = state;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "send_time", length = 19)
	public Date getSendTime() {
		return this.sendTime;
	}

	public void setSendTime(Date sendTime) {
		this.sendTime = sendTime;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "insert_time", length = 19)
	public Date getInsertTime() {
		return this.insertTime;
	}

	public void setInsertTime(Date insertTime) {
		this.insertTime = insertTime;
	}


}
